### ISSUE TITLE
Installation problems  

### ISSUE THREAD

**Issue by peterbebbington71** [HPI-Information-Systems/QuaggaLib#15]
After installing this package I try to run one of the examples and I get this error, please advise?

```
(quaggalib) ➜  QuaggaLib git:(master) ✗ python Examples/simpleExample.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "Examples/simpleExample.py", line 5, in <module>
    from Quagga import Quagga
  File "/anaconda2/envs/quaggalib/lib/python3.6/site-packages/Quagga-1.0-py3.6.egg/Quagga/__init__.py", line 2, in <module>
    from Quagga.__main__ import Quagga
  File "/anaconda2/envs/quaggalib/lib/python3.6/site-packages/Quagga-1.0-py3.6.egg/Quagga/__main__.py", line 2, in <module>
    from Quagga.Utils.BlockParser.BlockParser import BlockParser
ModuleNotFoundError: No module named 'Quagga.Utils.BlockParser'
```

**Comment by ben243871694** [comment]
Sorry it took me so long, didn't get a notification. If this is still relevant: the example was outdated, I updated it, it's on master.

**Comment by peterbebbington71** [comment]
This is Outdated, thank you for your response.
