### ISSUE TITLE
Unable to install quaggalib

### ISSUE THREAD

**Issue by aby0** [HPI-Information-Systems/QuaggaLib#17]
```
ERROR: Command errored out with exit status 1:
     command: /opt/textiq/SomPrivlog/t/textiq/SomPrivlog/Anaconda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i_aim9w1/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i_aim9w1/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-eczuv8_x
         cwd: /tmp/pip-install-i_aim9w1/markupsafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i_aim9w1/markupsafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/opt/textiq/SomPrivlog/t/textiq/SomPrivlog/Anaconda/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Looks like the package is not updated with latest changes. Tried to work around it by using older version of setuptools but tensorflow got broken then. Looks like you need to update the requirements,

**Comment by TimRepke** [comment]
Hi @aby0 ,
unfortunately, updating the dependencies would require rebuilding almost everything that touches tensorflow and retraining the model. Too many breaking changes... Apparently, we forgot to include a proper requirements file. Luckily, I still have the original virtualenv, these are the exact versions that we used:
```
absl-py==0.3.0
astor==0.7.1
autopep8==1.3.5
bleach==1.5.0
click==6.7
cycler==0.10.0
dateparser==0.7.0
Flask==1.0.2
gast==0.2.0
grpcio==1.14.0
h5py==2.8.0
html5lib==0.9999999
itsdangerous==0.24
Jinja2==2.10
Keras==2.2.0
Keras-Applications==1.0.2
keras-contrib==2.0.8
Keras-Preprocessing==1.0.1
kiwisolver==1.0.1
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.2.2
nose==1.3.7
numpy==1.15.1
pandas==0.23.3
protobuf==3.6.0
pycodestyle==2.4.0
pyparsing==2.2.0
python-dateutil==2.7.3
python-Levenshtein==0.12.0
pytz==2018.5
PyYAML==3.13
regex==2018.8.29
scikit-learn==0.19.2
scipy==1.1.0
six==1.11.0
sklearn==0.0
tensorflow==1.5.0
tensorflow-tensorboard==1.5.1
termcolor==1.1.0
tzlocal==2.0.0b1
Werkzeug==0.14.1
```
Conda should be able to install these.

**Comment by aby0** [comment]
@TimRepke Thanks. I will try to give it a go again. Will let you know if I was able to work through it.

**Comment by TimRepke** [comment]
Hi @aby0 , thanks for the update. I'm planning to update the repository in November. We are also getting requests by email, so it makes sense to keep this compatible with up-to-date systems and easier to use.

**Comment by benrobby** [comment]
Hi,

it looks like some dependency broke and the ci pipeline agrees.
We actually don't use a requirements.txt but you can find all dependency versions that it used to work with in the setup.py that we use to distribute the lib.

Cheers,
Ben
